[workspace]
authors = ["Ibrahim Boudaouara <158514881+iboudaouara@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "zarr-mycodec"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
zarr = ">=3.1.5,<4"
fsspec = ">=2026.3.0,<2027"
pytest = ">=9.0.3,<10"
pytest-asyncio = ">=1.3.0,<2"
numpy = ">=2.4.3,<3"

[pypi-dependencies]
zarr-mycodec = { path = ".", editable = true }

[activation]
scripts = ["activate_librmn.sh"]
